# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16xFYs8F1NDktKlhrqReNZoKM5_jL4VvU
"""

!pip install numpy matplotlib

import numpy as np
import matplotlib.pyplot as plt

def lerp(v0, v1, t):
    return (1 - t) * v0 + t * v1
def diagonal_gradient(size,color1,color2):

  image = np.zeros((size, size, 3), dtype="uint8")
  assert image.shape[0] == image.shape[1]
  x = np.linspace(0, 1, size)
  y = np.linspace(0, 1, size)
  X, Y = np.meshgrid(x, y)
  t = (X + Y) / 2
  for channel in range(3):
        image[:, :, channel] = lerp(color1[channel], color2[channel], t)
  return image


size = 100
color2 = [255, 128, 0]
color1 = [0, 128, 255]
gradient = diagonal_gradient(size, color1, color2)

plt.figure(1)
plt.imshow(gradient)
plt.show()